### ISSUE TITLE
[common-api] release v2

### ISSUE THREAD

**Issue by Alice52** [Alice52/common-api#161]
- #107 [common-api] release 

## maven release action

1. [生成 gpg key(`pub后的`)并将其发布到公网服务器](https://github.com/Alice52/common-api/issues/107#issuecomment-1723817874)
    - PUBLISH_GPG_PASSWORD: 生成gpgkey时的密码
    - PUBLISH_GPG_SECRET: 导出的密钥
2. maven 需要一下插件
    ```xml
    <profiles>
        <!-- mvn repository;-->
        <profile>
            <!-- 给 mvn 命令使用 指定 -P profile_name-->
            <id>sonatype-release</id>
            <activation>
                <jdk>[1.8,)</jdk>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>3.2.1</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <!-- please donot upgrade -->
                        <version>2.10.4</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <additionalparam>-Xdoclint:none</additionalparam>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>3.0.1</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.plugins</groupId>
                        <artifactId>nexus-staging-maven-plugin</artifactId>
                        <version>1.6.8</version>
                        <extensions>true</extensions>
                        <configuration>
                            <!-- must same as ossrh in distributionManagement/repository/id, and which set by release.yml' server_id -->
                            <serverId>ossrh</serverId>
                            <nexusUrl>https://s01.oss.sonatype.org/</nexusUrl>
                            <autoReleaseAfterClose>true</autoReleaseAfterClose>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
    ```

    ```xml
    <distributionManagement>
        <repository>
            <id>ossrh</id>
            <name>sonatype-nexus-staging</name>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
        <snapshotRepository>
            <id>sonatype-nexus-snapshots</id>
            <name>Nexus Snapshot Repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>

    </distributionManagement>
    ```
4. action 脚本
    ```yml
    jobs:
      publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
    
          - name: Set up Maven Central Repo
            uses: actions/setup-java@v1
            with:
              java-version: 1.8
              server-id: ossrh # 这个很重要需要和distributionManagement/repository/id一致(plugin内也一致)
              server-username: ${{ secrets.PUBLISH_OSSRH_USER }}
              server-password: ${{ secrets.PUBLISH_OSSRH_PASSWORD }}
              gpg-passphrase: ${{ secrets.PUBLISH_GPG_PASSWORD }}
    
          - name: Publish to Maven Central Repo
            uses: samuelmeuli/action-maven-publish@v1
            with:
              gpg_private_key: ${{ secrets.PUBLISH_GPG_SECRET }}
              gpg_passphrase: ${{ secrets.PUBLISH_GPG_PASSWORD }}
              nexus_username: ${{ secrets.PUBLISH_OSSRH_USER }}
              nexus_password: ${{ secrets.PUBLISH_OSSRH_PASSWORD }}
              maven_profiles: sonatype-release
              maven_goals_phases: clean deploy -DskipTests=true
        ```
6. 注意点
    - server_id 需要一致: 
        1. action/actions/setup-java@v1/server-id : 在 maven 的xml 中创建 server 块并指定 serverid
        2. distributionManagement/repository/id 
        3. nexus-staging-maven-plugin/serverId
  
7. 校验
    - https://s01.oss.sonatype.org/#stagingRepositories 在发布后可以看见(但是结束后无论成功还是失败都会消失)
    - https://s01.oss.sonatype.org/#view-repositories;releases~browsestorage~io/github/alice52: 成功后可以看见, 半天之后可以在 https://mvnrepository.com/search?q=io.github.alice52 看见
